# -*- coding: utf-8 -*-
"""embedding_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yowgBBjG488KEcAfqfW80a0PwRpySfc5
"""

!pip install sentence-transformers pandas pyarrow scikit-learn emoji tqdm

import os
import pandas as pd
import numpy as np
import emoji
from google.colab import drive
from sentence_transformers import SentenceTransformer
from tqdm.auto import tqdm
from sklearn.metrics.pairwise import cosine_similarity

drive.mount('/content/drive')

model = SentenceTransformer('sentence-transformers/all-distilroberta-v1', device='cuda')

base_path = "/content/drive/MyDrive/Reddit_Project/embedding_data"
subreddits_folders = [f for f in os.listdir(base_path) if f.startswith("subreddit=")]

print(f"Tổng hợp {len(subreddits_folders)} Subreddits")

subreddit_vectors = []

for sub_folder in tqdm(subreddits_folders, desc="Processing"):
    sub_name = sub_folder.split("=")[1]
    folder_path = os.path.join(base_path, sub_folder)

    try:
        df_sub = pd.read_parquet(folder_path)
    except Exception:
        continue

    if df_sub.empty or 'title' not in df_sub.columns:
        continue

    df_sub['title'] = df_sub['title'].astype(str).apply(lambda x: emoji.demojize(x, delimiters=(" ", " ")))
    titles = df_sub['title'].dropna().tolist()

    if not titles:
        continue

    embeddings = model.encode(titles, batch_size=128, show_progress_bar=False)
    mean_vec = np.mean(embeddings, axis=0)

    subreddit_vectors.append({
        'subreddit': sub_name,
        'mean_embedding': mean_vec
    })

df_vectors = pd.DataFrame(subreddit_vectors)

print("\nHoàn thành embedding")

print("Tính độ tương đồng Cosine")

emb_matrix = np.stack(df_vectors['mean_embedding'].values)
subreddits_list = df_vectors['subreddit'].tolist()

sim_matrix = cosine_similarity(emb_matrix)

results = []
num_subs = len(subreddits_list)

for i in range(num_subs):
    for j in range(i + 1, num_subs):
        score = sim_matrix[i][j]
        if score > 0.3:
            results.append({
                "Subreddit_A": subreddits_list[i],
                "Subreddit_B": subreddits_list[j],
                "Similarity_Score": round(float(score), 4)
            })

df_results = pd.DataFrame(results)
df_results_sorted = df_results.sort_values(by="Similarity_Score", ascending=False).reset_index(drop=True)

save_path = "/content/drive/MyDrive/Reddit_Project/subreddit_similarity_results.csv"
df_results_sorted.to_csv(save_path, index=False)

print(f"File được lưu tại: {save_path}")